name: MERN CI

on:
  push:
    branches: [main]

jobs:

  mongo-init-backend-test:

    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout Repository into GH runner
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Waiting for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
            echo "MongoDB is UP."
        
      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js
        
      - name: Running Backend test
        working-directory: ./backend
        run: |
          npm test
  
